// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type BrokenLink struct {
	ID         int64  `json:"id"`
	UrlID      int64  `json:"url_id"`
	Link       string `json:"link"`
	StatusCode int32  `json:"status_code"`
}

type Url struct {
	ID            int64          `json:"id"`
	Url           string         `json:"url"`
	Title         sql.NullString `json:"title"`
	HtmlVersion   sql.NullString `json:"html_version"`
	InternalLinks int32          `json:"internal_links"`
	ExternalLinks int32          `json:"external_links"`
	BrokenLinks   int32          `json:"broken_links"`
	HasLoginForm  bool           `json:"has_login_form"`
	// queued, running, done, error
	Status    string       `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}
