// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/foyez/url-inspector/backend/internal/models"
)

type BrokenLink struct {
	ID         int64  `json:"id"`
	UrlID      int64  `json:"url_id"`
	Link       string `json:"link"`
	StatusCode int32  `json:"status_code"`
}

type HeadingCount struct {
	ID      int64 `json:"id"`
	UrlID   int64 `json:"url_id"`
	H1Count int32 `json:"h1_count"`
	H2Count int32 `json:"h2_count"`
	H3Count int32 `json:"h3_count"`
	H4Count int32 `json:"h4_count"`
	H5Count int32 `json:"h5_count"`
	H6Count int32 `json:"h6_count"`
}

type Url struct {
	ID            int64  `json:"id"`
	Url           string `json:"url"`
	Title         string `json:"title"`
	HtmlVersion   string `json:"html_version"`
	InternalLinks int32  `json:"internal_links"`
	ExternalLinks int32  `json:"external_links"`
	BrokenLinks   int32  `json:"broken_links"`
	HasLoginForm  bool   `json:"has_login_form"`
	// queued, running, done, error
	Status    models.CrawlStatus `json:"status"`
	CreatedAt sql.NullTime       `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
}
